#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 28 19:18:01 2021

@author: alegretti
"""
import numpy as np

def loadGrid_BFS(volNumb,Le,Ls,ER,beta):
    """
    Import grid properties by loading 'gridData.npz' file generated by 'grid.py' routine
    """
    data = np.load('./grids/BFS/ER={}/beta={}/gridData_{}_volumes_Le={}_Ls={}_ER={}.npz'.format(ER,beta,volNumb,Le,Ls,ER))
    nx1 = data['nx1']
    nx2 = data['nx2']
    nx3 = data['nx3']
    ny1 = data['ny1']
    ny2 = data['ny2']
    ny3 = data['ny3']
    volArr = data['volArr']
    wallFunc = data['wallFunc']
    volNodes = data['volNodes']
    nodesCoord = data['nodesCoord']
    CVdata = data['CVdata']
    x1 = data['x1']
    x2 = data['x2']
    x3 = data['x3']
    y1 = data['y1']
    y2 = data['y2']
    y3 = data['y3']
    e = data['e']
    edgeVol = data['edgeVol']
    volNumb = data['volNumb']
    nodeNumb = data['nodeNumb']
    Le = data['Le']
    Ls = data['Ls']
    S = data['S']
    
    nx1,nx2,nx3,ny1,ny2,ny3,e,edgeVol,volNumb,nodeNumb = int(nx1),int(nx2),int(nx3),int(ny1),int(ny2),int(ny3),int(e),int(edgeVol),int(volNumb),int(nodeNumb)
    S = float(S)
    
    return nx1,nx2,nx3,ny1,ny2,ny3,volArr,volNodes,nodesCoord,x1,x2,x3,y1,y2,y3,e,edgeVol,CVdata,volNumb,nodeNumb,Le,Ls,S,wallFunc

def loadGrid_PP(Le,h,volNumb,nx,ny):
    """
    Import grid properties by loading 'gridData.npz' file generated by 'grid.py' routine
    """
    data = np.load('./grids/PP/gridData_L={:.1f}_h={}_nx={}_ny={}_{}volumes.npz'.format(Le,h,nx,ny,volNumb))
    nx1 = data['nx1']
    ny1 = data['ny1']
    volArr = data['volArr']
    wallFunc = data['wallFunc']
    volNodes = data['volNodes']
    nodesCoord = data['nodesCoord']
    CVdata = data['CVdata']
    x1 = data['x1']
    y1 = data['y1']
    volNumb = data['volNumb']
    nodeNumb = data['nodeNumb']
    Le = data['Le']
    h = data['h']    
    
    volNumb,nodeNumb = int(volNumb),int(nodeNumb)
    
    return volArr,volNodes,nodesCoord,x1,y1,CVdata,volNumb,nodeNumb,Le,h,wallFunc

def loadGrid_LDC(volNumb,Le,h):
    """
    Import grid properties by loading 'gridData.npz' file generated by 'grid.py' routine
    """
    data = np.load('./grids/LDC/gridData_{}_volumes_L={}_h={}.npz'.format(volNumb,Le,h))
    nx1 = data['nx1']
    ny1 = data['ny1']
    volArr = data['volArr']
    wallFunc = data['wallFunc']
    volNodes = data['volNodes']
    nodesCoord = data['nodesCoord']
    CVdata = data['CVdata']
    x1 = data['x1']
    y1 = data['y1']
    volNumb = data['volNumb']
    nodeNumb = data['nodeNumb']
    Le = data['Le']
    h = data['h']    
    
    nx1,ny1,volNumb,nodeNumb = int(nx1),int(ny1),int(volNumb),int(nodeNumb)
    
    return nx1,ny1,volArr,volNodes,nodesCoord,x1,y1,CVdata,volNumb,nodeNumb,Le,h,wallFunc